### ISSUE TITLE
Issues with editor settings

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#21]
It seems any editor settings are only applied when you restart the application, is this intended?

**Comment by NilsSve** [comment]
Not intended, but the program needs to be restarted when some of the checkboxes are changed on the "Misc" tab page for the Scintilla Editor Properties dialog.

It is probably better to change the logic so that the warning message to restart the application - that is shown when the "OEM to ANSI translation" is changed - are applied for all changes made on that tab page.

**Comment by NilsSve** [comment]
The save behaviour has been changed into always inform the user that changes has been made and that the application needs to be restarted.
I now close this issue.
