### ISSUE TITLE
'ChangeTrimCommandToFunction' missing 'to' keyword

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#38]
When executing this refactor function on the following code:

```
String sString
    
Move "teststring                " to sString
Trim sString
```

the output is:

```
String sString
    
Move "teststring                " to sString
Move (Trim(sString))  sString
```

As you can see, the 'to' keyword is missing in the second snippet.

**Comment by NilsSve** [comment]
At first, I was puzzled about this, but it then dawned upon me that the problem is caused by an invalid source line.
No DataFlex compiler would let through this line;
`    Trim sString`
Instead it should be;
`    Trim sString To sString`

After that change, the refactoring function works as expected.
I think we can safely close this issue.

**Comment by Caeylinity** [comment]
Fair enough. I suppose my limited old-style DF code knowledge is shining through here, apologies.

**Comment by NilsSve** [comment]
No worries. But it can be really helpful to test-compile the refactored file by pressing F5. The error dialog will then show where there are problems.
Closing this issue again now.
